//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDBrowserServiceCode.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class idCatalogItemDefinition
    {
        public string GUID { get; set; }
        public string CatalogItemGUID { get; set; }
        public Nullable<System.DateTime> idAssigned { get; set; }
    
        public virtual idCatalogItem idCatalogItem { get; set; }
        public virtual idProp idProp { get; set; }
    }
}
