//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDBrowserServiceCode.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class idCatalogItemDefinition
    {
        public string GUID { get; set; }
        public string CatalogItemGUID { get; set; }
        public Nullable<System.DateTime> idAssigned { get; set; }
    
        public virtual idCatalogItem idCatalogItem { get; set; }
        public virtual idProp idProp { get; set; }
    }
}
