//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDBrowserServiceCode.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class idCollectionInfo
    {
        public string GUID { get; set; }
        public string CollectionSource { get; set; }
        public string CollectionName { get; set; }
        public string CollectionDescription { get; set; }
        public string CollectionHotItemGUID { get; set; }
        public string LastSort { get; set; }
        public string ViewStyle { get; set; }
        public string LastSortOrder { get; set; }
        public string LastUsedTemplate { get; set; }
        public string LastUsedFTPDir { get; set; }
        public string LastUsedTargetDir { get; set; }
    }
}
