//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDBrowserServiceCode.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class idCollectionInfo
    {
        public string GUID { get; set; }
        public string CollectionSource { get; set; }
        public string CollectionName { get; set; }
        public string CollectionDescription { get; set; }
        public string CollectionHotItemGUID { get; set; }
        public string LastSort { get; set; }
        public string ViewStyle { get; set; }
        public string LastSortOrder { get; set; }
        public string LastUsedTemplate { get; set; }
        public string LastUsedFTPDir { get; set; }
        public string LastUsedTargetDir { get; set; }
    }
}
