//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDBrowserServiceCode.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class idFilePath
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public idFilePath()
        {
            this.idCatalogItem = new HashSet<idCatalogItem>();
            this.idImageVersion = new HashSet<idImageVersion>();
        }
    
        public string guid { get; set; }
        public string MediumType { get; set; }
        public string MediumName { get; set; }
        public Nullable<double> MediumSerial { get; set; }
        public string FilePath { get; set; }
        public string RootName { get; set; }
        public Nullable<int> PathState { get; set; }
        public Nullable<System.DateTime> idSignatureDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<idCatalogItem> idCatalogItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<idImageVersion> idImageVersion { get; set; }
    }
}
