//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDBrowserServiceCode.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class idImageCollection
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public idImageCollection()
        {
            this.idImageCollectionItem = new HashSet<idImageCollectionItem>();
        }
    
        public string GUID { get; set; }
        public string ParentGUID { get; set; }
        public string CollectionName { get; set; }
        public string CollectionDescription { get; set; }
        public string CollectionSource { get; set; }
        public Nullable<int> Locked { get; set; }
        public string Remark { get; set; }
        public string UDF1 { get; set; }
        public string UDF2 { get; set; }
        public string UDF3 { get; set; }
        public string UDF4 { get; set; }
        public string UDF5 { get; set; }
        public string LastUsedTemplate { get; set; }
        public string LastUsedFTPDir { get; set; }
        public string LastUsedTargetDir { get; set; }
        public string GalleryGUID { get; set; }
        public Nullable<int> GalleryOrder { get; set; }
        public Nullable<int> ParentOrder { get; set; }
        public Nullable<System.DateTime> idCreated { get; set; }
        public Nullable<System.DateTime> idOpen { get; set; }
        public Nullable<System.DateTime> idClose { get; set; }
        public Nullable<System.DateTime> idEnd { get; set; }
        public Nullable<int> lft { get; set; }
        public Nullable<int> rgt { get; set; }
        public byte[] idImage { get; set; }
        public string idCreatorGUID { get; set; }
    
        public virtual idImageGallery idImageGallery { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<idImageCollectionItem> idImageCollectionItem { get; set; }
    }
}
