//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDBrowserServiceCode.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class idImageData
    {
        public string GUID { get; set; }
        public string ImageGUID { get; set; }
        public string DataName { get; set; }
        public Nullable<System.DateTime> idCreated { get; set; }
        public Nullable<System.DateTime> idUpdated { get; set; }
        public string Extension { get; set; }
        public byte[] idData { get; set; }
        public Nullable<int> idMarked { get; set; }
        public string idHashKey { get; set; }
    }
}
