//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDBrowserServiceCode.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class idImageCollectionItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public idImageCollectionItem()
        {
            this.idImageScore = new HashSet<idImageScore>();
        }
    
        public string GUID { get; set; }
        public string ItemGUID { get; set; }
        public Nullable<int> CollectionOrder { get; set; }
        public Nullable<int> HotItem { get; set; }
    
        public virtual idCatalogItem idCatalogItem { get; set; }
        public virtual idImageCollection idImageCollection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<idImageScore> idImageScore { get; set; }
    }
}
