//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDBrowserServiceCode.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class idImageGallery
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public idImageGallery()
        {
            this.idImageCollection = new HashSet<idImageCollection>();
        }
    
        public string GUID { get; set; }
        public string ModelGUID { get; set; }
        public string GalleryName { get; set; }
        public string LastUsedTemplate { get; set; }
        public string LastUsedFTPDir { get; set; }
        public string LastUsedTargetDir { get; set; }
        public Nullable<int> LastOpenState { get; set; }
        public Nullable<int> ModelOrder { get; set; }
        public Nullable<System.DateTime> idCreated { get; set; }
        public byte[] idImage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<idImageCollection> idImageCollection { get; set; }
        public virtual idImageModel idImageModel { get; set; }
    }
}
