//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDBrowserServiceCode.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class idImageArea
    {
        public string GUID { get; set; }
        public string ImageGUID { get; set; }
        public string PropGUID { get; set; }
        public string idCaption { get; set; }
        public Nullable<double> idPosLeft { get; set; }
        public Nullable<double> idPosTop { get; set; }
        public Nullable<double> idPosRight { get; set; }
        public Nullable<double> idPosBottom { get; set; }
        public string idPosDescription { get; set; }
        public Nullable<double> idColor { get; set; }
        public Nullable<int> idIsFaceDetected { get; set; }
        public byte[] idFaceTemplate { get; set; }
        public Nullable<int> idHasFaceTemplate { get; set; }
        public Nullable<int> idHasFaceFeatures { get; set; }
        public Nullable<int> idIsFace { get; set; }
        public Nullable<int> idIsFaceRecognized { get; set; }
    }
}
