//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDBrowserServiceCode.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class idImageData
    {
        public string GUID { get; set; }
        public string ImageGUID { get; set; }
        public string DataName { get; set; }
        public Nullable<System.DateTime> idCreated { get; set; }
        public Nullable<System.DateTime> idUpdated { get; set; }
        public string Extension { get; set; }
        public byte[] idData { get; set; }
        public Nullable<int> idMarked { get; set; }
        public string idHashKey { get; set; }
    }
}
