//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDBrowserServiceCode.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class idImageModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public idImageModel()
        {
            this.idImageGallery = new HashSet<idImageGallery>();
        }
    
        public string GUID { get; set; }
        public string ModelName { get; set; }
        public string LastUsedTemplate { get; set; }
        public string LastUsedFTPDir { get; set; }
        public string LastUsedTargetDir { get; set; }
        public string UserGUID { get; set; }
        public Nullable<System.DateTime> idCreated { get; set; }
        public string idPassword { get; set; }
        public byte[] idImage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<idImageGallery> idImageGallery { get; set; }
        public virtual idUser idUser { get; set; }
    }
}
