//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDBrowserServiceCode.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class idPlaceHolder
    {
        public string GUID { get; set; }
        public string PlaceHolder { get; set; }
        public Nullable<int> PlaceHolderType { get; set; }
        public Nullable<int> idOrder { get; set; }
        public Nullable<int> idVisible { get; set; }
        public byte[] idImage { get; set; }
    }
}
