//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDBrowserServiceCode.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class idPropCategory
    {
        public string GUID { get; set; }
        public string CategoryName { get; set; }
        public Nullable<int> IsPrivate { get; set; }
        public Nullable<double> idUseColor { get; set; }
        public Nullable<double> idColor { get; set; }
        public Nullable<double> idFontColor { get; set; }
        public Nullable<int> idOrder { get; set; }
        public byte[] idImage { get; set; }
    }
}
