//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDBrowserServiceCode.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class idPropRelation
    {
        public string GUID { get; set; }
        public string ParentGUID { get; set; }
        public string ChildGUID { get; set; }
        public string ParentRule { get; set; }
        public string ChildRule { get; set; }
        public Nullable<System.DateTime> idCreated { get; set; }
    
        public virtual idProp idProp { get; set; }
    }
}
