//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDBrowserServiceCode.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class idPropGroup
    {
        public string GUID { get; set; }
        public string GroupName { get; set; }
        public Nullable<int> GroupStyle { get; set; }
        public Nullable<int> InclHierarchical { get; set; }
        public Nullable<int> ExclHierarchical { get; set; }
        public string UserGUID { get; set; }
        public Nullable<System.DateTime> idCreated { get; set; }
        public string idRatings { get; set; }
        public string idLabels { get; set; }
        public string idExclRatings { get; set; }
        public string idExclLabels { get; set; }
        public Nullable<int> WithRange { get; set; }
        public Nullable<System.DateTime> RangeFrom { get; set; }
        public Nullable<System.DateTime> RangeTo { get; set; }
        public string idFileTypes { get; set; }
        public string idExclFileTypes { get; set; }
        public string GroupType { get; set; }
        public string idPlaceHolders { get; set; }
        public string idExclPlaceHolders { get; set; }
        public string idCategories { get; set; }
        public string idExclCategories { get; set; }
        public string idCollections { get; set; }
        public string idExclCollections { get; set; }
        public string idGalleries { get; set; }
        public string idExclGalleries { get; set; }
        public string idAlbums { get; set; }
        public string idExclAlbums { get; set; }
        public string idGroups { get; set; }
        public string idExclGroups { get; set; }
        public string idMetaOcc { get; set; }
        public string idExclMetaOcc { get; set; }
        public string idMeta { get; set; }
        public string idExclMeta { get; set; }
        public string idStates { get; set; }
        public string idExclStates { get; set; }
        public string idFreeSearch { get; set; }
        public string idExclFreeSearch { get; set; }
    
        public virtual idUser idUser { get; set; }
    }
}
