//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDBrowserServiceCode.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class idPropRelation
    {
        public string GUID { get; set; }
        public string ParentGUID { get; set; }
        public string ChildGUID { get; set; }
        public string ParentRule { get; set; }
        public string ChildRule { get; set; }
        public Nullable<System.DateTime> idCreated { get; set; }
    
        public virtual idProp idProp { get; set; }
    }
}
