//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDBrowserServiceCode.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class idSyncImageIPTC
    {
        public string GUID { get; set; }
        public string ImageGUID { get; set; }
        public string IPTC_TagName { get; set; }
        public string IPTC_TagValue { get; set; }
        public Nullable<System.DateTime> RequestMoment { get; set; }
    }
}
