//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDBrowserServiceCode.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class idSyncImageIPTC
    {
        public string GUID { get; set; }
        public string ImageGUID { get; set; }
        public string IPTC_TagName { get; set; }
        public string IPTC_TagValue { get; set; }
        public Nullable<System.DateTime> RequestMoment { get; set; }
    }
}
