//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDBrowserServiceCode.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class idThumbs
    {
        public string GUID { get; set; }
        public string ImageGUID { get; set; }
        public string idType { get; set; }
        public string FileName { get; set; }
        public string MediumType { get; set; }
        public string MediumName { get; set; }
        public Nullable<float> MediumSerial { get; set; }
        public byte[] idThumb { get; set; }
    }
}
