//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDBrowserServiceCode.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class idThumbs
    {
        public string GUID { get; set; }
        public string ImageGUID { get; set; }
        public string idType { get; set; }
        public string FileName { get; set; }
        public string MediumType { get; set; }
        public string MediumName { get; set; }
        public Nullable<float> MediumSerial { get; set; }
        public byte[] idThumb { get; set; }
    }
}
