//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDBrowserServiceCode.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class idUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public idUser()
        {
            this.idCatalogItem = new HashSet<idCatalogItem>();
            this.idImageCard = new HashSet<idImageCard>();
            this.idImageComment = new HashSet<idImageComment>();
            this.idImageModel = new HashSet<idImageModel>();
            this.idImageScore = new HashSet<idImageScore>();
            this.idImageSubscription = new HashSet<idImageSubscription>();
            this.idProp = new HashSet<idProp>();
            this.idPropGroup = new HashSet<idPropGroup>();
            this.idUserFavorite = new HashSet<idUserFavorite>();
            this.idUserUsage = new HashSet<idUserUsage>();
            this.idUserUser = new HashSet<idUserUser>();
            this.idUserUser1 = new HashSet<idUserUser>();
            this.idUserProp = new HashSet<idUserProp>();
            this.idImageBox = new HashSet<idImageBox>();
        }
    
        public string GUID { get; set; }
        public string idUserName { get; set; }
        public string idPassword { get; set; }
        public string FullUserName { get; set; }
        public string DefaultShare { get; set; }
        public Nullable<int> CatalogOwner { get; set; }
        public Nullable<int> UserOwner { get; set; }
        public Nullable<int> ImageOwner { get; set; }
        public string EMailAddress { get; set; }
        public Nullable<System.DateTime> LastInlog { get; set; }
        public string UDF1 { get; set; }
        public string UDF2 { get; set; }
        public string UDF3 { get; set; }
        public string UDF4 { get; set; }
        public string UDF5 { get; set; }
        public Nullable<System.DateTime> FirstInlog { get; set; }
        public Nullable<System.DateTime> PrevInlog { get; set; }
        public string LastIP { get; set; }
        public Nullable<System.DateTime> idCreated { get; set; }
        public string WebAddress { get; set; }
        public Nullable<long> idQuota { get; set; }
        public Nullable<System.DateTime> idQuotaExpires { get; set; }
        public Nullable<long> idDiskQuota { get; set; }
        public Nullable<System.DateTime> idDiskQuotaExpires { get; set; }
        public Nullable<long> idDiskUsage { get; set; }
        public string idUserType { get; set; }
        public Nullable<int> FailedLoginCount { get; set; }
        public Nullable<System.DateTime> LoginLockExpires { get; set; }
        public Nullable<System.DateTime> LastFailedLogin { get; set; }
        public Nullable<int> TimezoneOffset { get; set; }
        public Nullable<int> idProtected { get; set; }
        public Nullable<int> idPublished { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<idCatalogItem> idCatalogItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<idImageCard> idImageCard { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<idImageComment> idImageComment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<idImageModel> idImageModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<idImageScore> idImageScore { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<idImageSubscription> idImageSubscription { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<idProp> idProp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<idPropGroup> idPropGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<idUserFavorite> idUserFavorite { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<idUserUsage> idUserUsage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<idUserUser> idUserUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<idUserUser> idUserUser1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<idUserProp> idUserProp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<idImageBox> idImageBox { get; set; }
    }
}
