//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDBrowserServiceCode.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class idUserFavorite
    {
        public string GUID { get; set; }
        public string ImageGUID { get; set; }
        public Nullable<System.DateTime> idMoment { get; set; }
        public string UserGUID { get; set; }
    
        public virtual idCatalogItem idCatalogItem { get; set; }
        public virtual idUser idUser { get; set; }
    }
}
