//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDBrowserServiceCode.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_AlbumVersion
    {
        public string GUID { get; set; }
        public string MainImageGUID { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string VersionName { get; set; }
        public string FileName { get; set; }
        public Nullable<int> FileSize { get; set; }
        public Nullable<System.DateTime> FileStamp { get; set; }
        public Nullable<int> Rating { get; set; }
        public string idLabel { get; set; }
        public Nullable<int> idInSync { get; set; }
        public Nullable<int> idBookmark { get; set; }
        public Nullable<int> idFileNameLen { get; set; }
        public string PathGUID { get; set; }
        public string idFileType { get; set; }
        public string GroupGUID { get; set; }
        public Nullable<int> GroupOrder { get; set; }
        public Nullable<double> idGPSLon { get; set; }
        public Nullable<double> idGPSLat { get; set; }
        public Nullable<double> idGPSAlt { get; set; }
        public Nullable<int> idHasRecipe { get; set; }
        public string idSignature { get; set; }
        public Nullable<int> PlaceHolderType { get; set; }
        public string PlaceHolder { get; set; }
        public Nullable<int> idVersionCount { get; set; }
        public int idMainVersion { get; set; }
        public Nullable<int> idPropCount { get; set; }
        public string MediumType { get; set; }
        public string MediumName { get; set; }
        public Nullable<double> MediumSerial { get; set; }
        public string FullFileName { get; set; }
        public string FilePath { get; set; }
    }
}
