//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDBrowserServiceCode.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_CatalogItem
    {
        public string GUID { get; set; }
        public string FileName { get; set; }
        public Nullable<System.DateTime> DateTimeStamp { get; set; }
        public Nullable<int> FileSize { get; set; }
        public Nullable<System.DateTime> FileStamp { get; set; }
        public Nullable<int> Rating { get; set; }
        public string ImageName { get; set; }
        public string ImageDescription { get; set; }
        public string UDF1 { get; set; }
        public string UDF2 { get; set; }
        public string UDF3 { get; set; }
        public string UDF4 { get; set; }
        public string UDF5 { get; set; }
        public string UserGUID { get; set; }
        public Nullable<int> AutoCataloged { get; set; }
        public string ThumbFile { get; set; }
        public string SmallFile { get; set; }
        public string MediumFile { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public Nullable<System.DateTime> idCreated { get; set; }
        public Nullable<int> idCounter { get; set; }
        public Nullable<int> idMarked { get; set; }
        public string idLabel { get; set; }
        public Nullable<int> idInSync { get; set; }
        public Nullable<int> idBookmark { get; set; }
        public Nullable<int> idFileNameLen { get; set; }
        public string PathGUID { get; set; }
        public string idFileType { get; set; }
        public string GroupGUID { get; set; }
        public Nullable<int> GroupOrder { get; set; }
        public Nullable<double> idGPSLon { get; set; }
        public Nullable<double> idGPSLat { get; set; }
        public Nullable<double> idGPSAlt { get; set; }
        public Nullable<int> idHasRecipe { get; set; }
        public string idSignature { get; set; }
        public Nullable<int> idVersionCount { get; set; }
        public int idMainVersion { get; set; }
        public string MainGUID { get; set; }
        public Nullable<int> idPropCount { get; set; }
        public string MediumType { get; set; }
        public string MediumName { get; set; }
        public Nullable<double> MediumSerial { get; set; }
        public string FullFileName { get; set; }
        public string FilePath { get; set; }
    }
}
