//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDBrowserServiceCode.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_PlaceHolderVersion
    {
        public string GUID { get; set; }
        public string MainImageGUID { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string VersionName { get; set; }
        public string FileName { get; set; }
        public Nullable<int> FileSize { get; set; }
        public Nullable<System.DateTime> FileStamp { get; set; }
        public Nullable<int> Rating { get; set; }
        public string idLabel { get; set; }
        public Nullable<int> idInSync { get; set; }
        public Nullable<int> idBookmark { get; set; }
        public Nullable<int> idFileNameLen { get; set; }
        public string PathGUID { get; set; }
        public string idFileType { get; set; }
        public string GroupGUID { get; set; }
        public Nullable<int> GroupOrder { get; set; }
        public Nullable<double> idGPSLon { get; set; }
        public Nullable<double> idGPSLat { get; set; }
        public Nullable<double> idGPSAlt { get; set; }
        public Nullable<int> idHasRecipe { get; set; }
        public string idSignature { get; set; }
        public string PlaceHolderGUID { get; set; }
    }
}
