//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDBrowserServiceCode.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_PropCategory
    {
        public string GUID { get; set; }
        public string CategoryName { get; set; }
        public Nullable<int> IsPrivate { get; set; }
        public Nullable<double> idUseColor { get; set; }
        public Nullable<double> idColor { get; set; }
        public Nullable<double> idFontColor { get; set; }
        public Nullable<int> idOrder { get; set; }
        public byte[] idImage { get; set; }
        public Nullable<int> idPhotoCount { get; set; }
    }
}
