//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDBrowserServiceCode.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_VersionPlaceHolder
    {
        public string MainImageGUID { get; set; }
        public string ItemGUID { get; set; }
        public string PlaceHolderGUID { get; set; }
        public Nullable<System.DateTime> idCreated { get; set; }
        public string GUID { get; set; }
        public string PlaceHolder { get; set; }
        public Nullable<int> PlaceHolderType { get; set; }
        public Nullable<int> idOrder { get; set; }
        public Nullable<int> idVisible { get; set; }
    }
}
